version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  terraform: circleci/terraform@3.2.0

jobs:
  plan-apply:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: $AWS_DEFAULT_REGION
      - run:
          name: Terraform Init and Plan
          command: |
            terraform init -input=false
            terraform plan -out=tfapply -var-file=terraform.tfvars
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - .
  apply:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve tfapply

  plan-destroy:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: Terraform Plan Destroy
          command: terraform plan -destroy -out=tfdestroy -var-file=terraform.tfvars
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - .

  destroy:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /tmp/project
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: Terraform Destroy
          command: terraform apply -auto-approve tfdestroy

workflows:
  version: 2
  terraform_deploy:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply

    triggers:
      - push:
          branches:
            only:
              - master
